# 公共配置文件
spring:
  application:
    name: nowapi-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    # store-type: redis
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/now_api
    username: root
    password: 123456
  # Redis 配置
  #  redis:
  #    database: 1
  #    host: localhost
  #    port: 6379
  #    timeout: 5000
  #    password: 123456
  # Elasticsearch 配置
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:MM:ss
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
nowapi:
  client:
    access-key: xxx
    secret-key: xxx
  alipay:
    appId: 9021000131660368
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCaUeb0ex7JB+1dqJ7gGB4CH8RWz76IEFWbrq8aoB79cw/ltlpTvRajmQ0YXrg57ARRElvsJc9Evw/CIz1ccyN65GI1fEMZ5tKrPjiGUpm2iXfxnRgwPUlST0X+96YcoqvNPuXGjWWZAX+MVak7mBrSDtFnG+HTVeMYrZkPtxjcZ/qXAUAflzcNT6XH6/5uly4JfYLJGP3MBdjSVek2FV9haOt+XEUGeX4szNe8rF/6VxTzTSqSvKLtHTGy1U+4T3D+anBC+zuIhCKCGJ3vMR2TYfbHjFY9tDb7eQIMS6b3dS9drENoCe3GaEIsqPXcmULZgjsUKditkpZPXe5/qkN5AgMBAAECggEAL5pEG/Y+sNR5LALvv0CxQQZ7kivTIjWnsrZX3Wa3KIdtx/ZQNrSFX0G/AF13hqZ/TmLTaCzhmts1CTXFn9cEgswgX09Ng5foNFqlJQol0GDnVuiWpYrCK1m4xcWuv/aN+GoGhxDm3iPQLIHgCjoJS/K2NZAsQPylaN9j760TRilv2ABZ9afRs/vdXVSUqbCQdejc4XqK+JuEHyjP6NJMylMLDBdUxICx7zvgATdozKvkN988svlH4C1U53oLQM7ov3GICO25RavLju1A8pKBi4fiRG33ac8xlIxbuMVFFOJfPCUJFy5DsfjWOhZJvj1fAHb+oD30wvMwMAvTMr6rgQKBgQDyrLqKSxLwV5W5wazmQiAM/+20vi2lcxDSKvX0yklg7EhCDkVNJnHmmish0ohg9ChIBk55JzADq2uOE2W1me8VxkXs117bbZ+gJk3kh+NvVZD2aBNnQZI8B3Uhwyls+9ZBgIVIJ248hDp/vAzH8ig/gMhc8bqrk9h3bZfwJIK7FQKBgQCiyyw+nkungpj7AKZmtSmAYrG0/Y3ifSR6g40mJD81gmaYoc0BC5+SGmjJTQXIEI7TxFPVWw/g4maB07kdk90lPn78cyLHzJ7LkXlGoEuARgEMX6wLWndWlm9Bxz86KIGZfq5cc+CLRAvRzSWAbDm8J+wGkLLI/7EqfbvSaEzv1QKBgG0eqD6ZJWn3KDc/1FwxbbIKvrtgLKxRwkWO1cv9zeMMPC2ftx/K4rqbpjtuLK7T+uzwEQc/TMLJqPJY3Io9Lpmu7zBhY6DteTKNJsdVJzqf0jBKejca8AOYIt5MoGsGDsCjZsscF+CUYK2hRGoABIMRiIbql1Khh1ukZwavlC1FAoGAY5sSuEGcoqKavcF5DxC7ku1QNCCLxs+xGTESlQrKjg/6fFtLlt8oxHlaMgjph67x5QqUDNBJ19xOwhLsifdl8RrbEdXUqxE8++tHm/oKGDM9AvgqyUuSBy3GZyXlPs139pX3U2QnOK7q2HTABGKztLdsh9vTOH6SRSBnYmck4/0CgYEAyZmURhzH8lZVW1xNE2/pm8lgD6mfFtzbOBoHExgLH/frTAiAK2kosysNwQKXnIkdUHfJ9zWxU70d+QVrb0d922cCfE0FiIcEckbOIsW1TkKPDFhb8NEeUrp7M8WUuTolq3l7YEQS0hq3+bK+I+mU9OtZggDKCo0sC4j3leF1kfA=
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjBJElzi9amjyNXdnJP9dLZ+Huo2hsquGKqmR3MmiTJ08TmgpEW1Ta9lsJ7PfTJpObmpdOBjimmNsm4jrRXu5DyQOWa3wtYxyuBTw9qx52tHVN9oApzSCu6rvJ8EFPGV15ZuJx8OtG8+IyTRr93YBaXA3QCL4jrZKWzv3vF4pxGMTcKSb95yel6cfXjWHh/PkFNjB/5G9RXdFXbLjqK/OOuPy2HzrR3uOSo4CVnhtAvRKpP21BFN7+jKYRLjm1rZPJDU+/pPfUbyKBaqAaPx0kzNKhNkU7acyEvJ2FmgDB8+/9PmNR08z9Cq7Z6xPiDmCY9AgD82jmzm8WEM4AoxOAwIDAQAB
    server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    domian: http://e9e4pc.natappfree.cc
dubbo:
  application:
    name: nowapi-backend-provider
  protocol:
    name: dubbo
    port: -1 #随机分配可用端口
  registry:
    id: nacos-register
    address: nacos://localhost:8848